-- Apagar todas as tabelas do BD

/*
BEGIN
    FOR x IN (
        SELECT
            table_name
        FROM
            user_tables
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || x.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
*/

@ 'C:\oracle\script_modelo_pedido.SQL';

ALTER TABLE cidade MODIFY nom_cidade VARCHAR2(50);
ALTER TABLE pedido ADD status VARCHAR2(50);

-- 1°
/*
INSERT INTO pais SELECT * FROM pf1788.pais;
COMMIT;
INSERT INTO estado SELECT * FROM pf1788.estado;
COMMIT;
*/

INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;
 
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;
 
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;
 
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;
 
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;
 
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;
 
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;

INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;
 
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;
 
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;
 
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;
 
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;
 
-- 3. Tabela dependente de cliente, usuario, vendedor, endereco_cliente
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;
 
-- 4. Tabelas que dependem diretamente de pedido
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;
 
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;
 
-- 5. Por último, movimentação de estoque
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;